### ISSUE TITLE
"fetch is not defined" error

### ISSUE THREAD

**Issue by unimprobable** [ginlane/gatsby-source-yotpo-shopify#10]
Hello,
I am trying to run gatsby-source-yotpo-shopify, but am receiving the following error:
```
error
error an error occurred while sourcing data
error "gatsby-source-yotpo-shopify" threw an error while running the sourceNodes lifecycle:

fetch is not defined

  51 |   try {
  52 |     console.time((0, _utils.formatMsg)('finished fetching shopify products'));
> 53 |     const shopifyProducts = await (0, _fetch.getShopifyProducts)({
     |                                                                 ^
  54 |       shopifyClient
  55 |     });
  56 |     console.timeEnd((0, _utils.formatMsg)('finished fetching shopify products'));

Make sure that you don't have a typo somewhere and use valid arguments in sourceNodes lifecycle.
Learn more about sourceNodes here: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#sourceNodes
```

Any idea why this won't work for me? I am running Gatsby 3.1. Thanks!

**Comment by nowaczykm5** [comment]
I have also this issue :(

**Comment by code-mat** [comment]
I've got exactly the same issue :(

**Comment by thenotoriousjr** [comment]
Any updates? I have the same issue too.

**Comment by unimprobable** [comment]
@thenotoriousjr Try throttleup-gatsby-source-yotpo. I got that package to work for sourcing reviews.

**Comment by thenotoriousjr** [comment]
> @thenotoriousjr Try throttleup-gatsby-source-yotpo. I got that package to work for sourcing reviews.

Does it work with Shopify with the intention of building this component and importing it into individual product page?

**Comment by thenotoriousjr** [comment]
> @thenotoriousjr Yes, you can get the reviews sourced in GraphQL. Use them however you need in your components.

Any idea how to render the reviews for individual products? It seems like the plugin can’t query the reviews under ShopifyProduct as the queries return from the plugin are independent allYotpoProductReviews like so.

**Comment by trevlar** [comment]
This is related to using the Shopify web api version 2020-10 to 2021-10.
 v5 of gatsby-source-shopify uses the latest stable Shopify api.
 These will likely be considerations that will need to be taken for upgrading this plugin when it queries the product catalog from Shopify.
 
 https://github.com/gatsbyjs/gatsby/issues/32069
https://github.com/gatsbyjs/gatsby/discussions/32093

**Comment by dhunninghake** [comment]
Fixed with https://github.com/ginlane/gatsby-source-yotpo-shopify/commit/f3eac778fdeff762c9b4a057530827abe2985ba0
